---
title: "openaitools demo"
---


```{r}

if (!require(openaitools)) {
  devtools::install_github("damiencrone/openaitools")
  library(openaitools)
}

api_key = "sk-..." # Insert your API key here or load from file
# To get an API key, go to https://platform.openai.com/api-keys

```

```{r}

articles = readRDS(file = "data/en_mythical_creatures_corpus_processed.RDS")
result_list = list()

cat(articles["Hoop snake"])

```


```{r}

system_prompt = load_prompt("prompts/creature_coding_system_prompt.txt")

```

```{r}

cat(system_prompt)

```

```{r}

for (creature in names(articles)) {
  article = articles[[creature]]
  if (!creature %in% names(result_list)) {
    prompt_list = list(list(role = "system", content = system_prompt),
                       list(role = "user", content = article))
    json_response = get_json_response(api_key, prompt_list)
    result_list[[creature]] = json_response
  }
}

```

```{r}

print(result_list$`Drop bear`)

```

```{r}

print(result_list$`Hoop snake`)

```

```{r}

result_table = sapply(X = result_list,
                      FUN = function(x) {
                        return(c(name = x$name,
                                 size = x$size,
                                 dangerousness = x$dangerousness))
                      })
result_table = data.frame(t(result_table), row.names = NULL)
result_table$size = as.integer(result_table$size)
result_table$dangerousness = as.integer(result_table$dangerousness)
print(result_table[, 1:3])

```

```{r}

plot(x = result_table$size,
     y = result_table$dangerousness,
     xlim = c(0, 10),
     ylim = c(0, 10),
     xlab = "Size",
     ylab = "Dangerousness")
text(x = result_table$size,
     y = result_table$dangerousness,
     labels = result_table$name,
     pos = 3)

```

